spring:
  cloud:
    function:
      definition: sendOrder;receiveOrder
    stream:
      kafka:
        binder:
          brokers: localhost:9092      
      bindings: 
        sendOrder-out-0:
          destination: order-topic
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
        receiveOrder-in-0:
          destination: order-topic
          group: myGroup
          concurrency: 2
        receiveOrder-out-0:  
          destination: outland-order-topic
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
       